baseURL = 'https://aiyax.com/'
languageCode = 'zh-cn'
copyright = 'aiyax.com'
theme = 'ananke'
title = 'AIYAX'

DefaultContentLanguage = "cn"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
[languages.en]
# title = "Make technology services accessible to the masses"
languageName = "English"
weight = 1
contentDir = "content/en"
# languageDirection = 'rtl' for Right-To-Left languages
[languages.cn]
# title = "让科技服务普罗大众"
languageName = "简体中文"
weight = 2
contentDir = "content/cn"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
site_logo = "images/logo255_81.png"
text_color = ""
author = ""
favicon = ""
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-navy"
recent_posts_number = 3
record_number = "鲁ICP备2023017100号-1"
record_number_link = "https://beian.miit.gov.cn/"

[[menu.main]]
name = "公告"
url = "/announcement"
identifier = "announcement"
weight = 1
