baseURL = 'https://aiyax.com/'
languageCode = 'zh-cn'
copyright = 'aiyax.com'
theme = 'ananke'
title = 'AIYAX'

DefaultContentLanguage = "cn"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
[languages.en]
# title = "Make technology services accessible to the masses"
weight = 1
contentDir = "content/en"
# languageDirection = 'rtl' for Right-To-Left languages
[languages.cn]
# title = "让科技服务普罗大众"
weight = 2
contentDir = "content/cn"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
site_logo = "images/logo255_81.png"
text_color = ""
author = ""
favicon = ""
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-navy"
recent_posts_number = 3

# [[params.ananke_socials]]
# name = "twitter"
# url = "https://twitter.com/GoHugoIO"
